### ISSUE TITLE
Incorrect version of OMI for your system

### ISSUE THREAD

**Issue by purplekrayons** [Microsoft/omi#560] opened 2018-08-08 03:53 UTC
I receive the following error while trying to update omi.

Ubuntu 16.04 running from an Azure B2S VM.

```
The following packages will be upgraded:
  omi
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
17 not fully installed or removed.
Need to get 0 B/1,836 kB of archives.
After this operation, 16.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 120100 files and directories currently installed.)
Preparing to unpack .../archives/omi_1.4.3.1_amd64.deb ...
Expecting SSL version (compatible with): 1.0.0
SSL version found on system:             1.1.0h

Incorrect version of OMI for your system, please check SSL version.
dpkg: error processing archive /var/cache/apt/archives/omi_1.4.3.1_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 3
Deleting omi service account ...
userdel: user omi is currently used by process 2470
Deleting omi group ...
groupdel: cannot remove the primary group of user 'omi'

************************************************************
* Warning: The certificate and keyfile were not generated  *
* since they already exist.                                *
************************************************************
chgrp: invalid group: ‘omiusers’
2018-08-07 23:48:01 System already configured to run /opt/omi/bin/support/config_keytab_update.sh automatically
Configuring OMI service ...
Synchronizing state of omid.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable omid
Errors were encountered while processing:
 /var/cache/apt/archives/omi_1.4.3.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by JumpingYang001** [comment] 2018-08-08 06:51
This should be Microsoft deb repo issue, I don't manage it. @palladia @sarojcare, could you help to check it? thanks.

From the message, the deb repo on Ubuntu16.04 are showing always use 1.0.0 version while customer manually upgrade openssl upgraded to 1.1.1 version.

Another issue is that it seems after the openssl incorrect version, the installer continue to install.

@purplekrayons have you upgrade your openssl from 1.0.0 to 1.1.0 on your Ubuntu16 box? check `openssl version`

**Comment by JumpingYang001** [comment] 2018-08-08 06:58
@purplekrayons thanks for reporting it!
work around is to manually install the correct version: 
```
wget https://github.com/Microsoft/omi/releases/download/v1.4.3-1/omi-1.4.3-1.ssl_110.ulinux.x64.deb
dpkg -i omi-1.4.3-1.ssl_110.ulinux.x64.deb
```

**Comment by JumpingYang001** [comment] 2018-08-08 07:01
@palladia looks like the `apt update` from Microsoft repo doesn't check the `openssl version` to match correct package, and it now check the OS version is Ubuntu16.04 and provide an Ubuntu16.04 default package, any idea or solution to fix it?

**Comment by JumpingYang001** [comment] 2018-08-08 07:06
Since there are many customer or OS vendor might upgrade their openssl version, so it make a new issue for us now: there might be more than 1 openssl version which might install on same OS version now, in such way, we have to provide 2 different openssl version packages for Ubuntu16.04, and also maybe same issue on other OS.

**Comment by sarojcare** [comment] 2018-08-08 11:28
Whether output of comand "openssl version" reflects the version appropriately?

**Comment by purplekrayons** [comment] 2018-08-08 14:42
Thank you @JumpingYang001 

To address your questions:

1. I did not manually build and install openSSL 1.1.0h. I cannot say for sure how this version got on this server -- i assume through `apt upgrade` at some point.
2. `openssl version` reports: `OpenSSL 1.1.0h  27 Mar 2018`
3. The [Releases ](https://github.com/Microsoft/omi/releases) page does not reflect version `1.4.3-1` -- however, I can confirm this version installed successfully.

**Comment by JumpingYang001** [comment] 2018-08-08 21:47
@purplekrayons possiblely your os was upgraded to Ubuntu18? can you check `apt-cache policy openssl` , `cat /etc/*-release` and `lsb_release -r`?

**Comment by purplekrayons** [comment] 2018-08-08 21:51
`apt-cache policy openssl`
```
openssl:
  Installed: 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1
  Candidate: 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0h-2.0+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4.13 500
        500 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     1.0.2g-1ubuntu4 500
        500 http://azure.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

`cat /etc/*-release`
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

`lsb_release -r`
```
Release:        16.04
```

**Comment by JumpingYang001** [comment] 2018-08-08 22:58
@purplekrayons you are using private built packages repository from http://ppa.launchpad.net/ondrej/php , that's not official repo.

we only support official repo now, if you use private repo, there is a work around is to install correct omi manually, I'd like to close this issue, thanks.

**Closed by JumpingYang001** 2018-08-08 22:58 UTC

**Comment by panzer-planet** [comment] 2019-06-11 14:05
I am using official ubuntu packages and I'm also having this issue. Is OMI bloatware MS is shipping on Azure Ubuntu images? Can I just remove OMI? I've used Ubuntu for 15 years and I've never heard of it.

**Comment by purplekrayons** [comment] 2019-06-11 18:17
Omi is a toolkit used by the Azure team for collecting and reporting diagnostics on your VM. I wouldn't exactly refer to it as bloatware. I can confirm that yes, if you want, you can uninstall Omi:
`sudo apt purge --auto-remove omi`

If your issue is the same as mine, then it means you've installed PHP from the Ondrej/PHP repo and you've likely got the 1.1.x branch of OpenSSL with additional updates (letter at the end). The latest of which is `j` ([more here](https://www.openssl.org/news/openssl-1.1.0-notes.html)). The team above said they do not support private PHP packages. Based on this, i'm _guessing_ that the official PHP repo is using the base `1.1.0` or `1.0.0` versions of openssl, whereas Ondrej's repo contains updated versions (in my particular case, `1.1.0h`.

As such, my _assumption_ here is that this repository installer simply does not support newer versions of openssl found in Ondrej's repo.

You would need to manually keep Omi up-to-date by downloading the ssl_110 flavour of releases. You can find them from the [Releases Page](https://github.com/Microsoft/omi/releases), or [directly here](https://github.com/microsoft/omi/releases/download/v1.6.0/omi-1.6.0-0.ssl_110.ulinux.x64.deb). Install the package using dpkg: `sudo dpkg -i omi-1.6.0-0.ssl_110.ulinux.x64.deb`

Typically, when I perform my system updates, i'll just hold the Omi update, perform my system updates, then unhold Omi and proceed to update manually.

```bash
sudo apt update
sudo apt-mark hold omi
sudo apt upgrade
sudo apt-mark unhold omi
cd ~
wget https://github.com/microsoft/omi/releases/download/v1.6.0/omi-1.6.0-0.ssl_110.ulinux.x64.deb
sudo dpkg -i omi-1.6.0-0.ssl_110.ulinux.x64.deb
```

**Comment by JumpingYang001** [comment] 2019-06-12 03:25
apt upgrade pick up openssl100 version of omi, because current omi is openssl100 version.
And php repo installed openssl110 on the system, so when apt install openssl100 version of omi, it show the error, that say, apt determine upgrade openssl100 version of omi due to `exist omi is openssl100 version`.

there is no way to fix on omi side for this issue.
once you remove openssl100 version of omi and install openssl110 version, it will not happen again.
On Azure, LAD(Linux Azure Diagnostic) and OMS(Operation Management Suite) will install omi.

**Comment by purplekrayons** [comment] 2019-06-13 16:35
Unfortunately, that is not the behavior i'm seeing.
I do not have the ssl100 version of Omi installed, I have the ssl110 version which I manually installed (omi-1.6.0-0.ssl_110.ulinux.x64.deb).

Today I performed system updates and chose not to hold the omi update so I can show you what happens:

![omi-update](https://user-images.githubusercontent.com/9218035/59449902-12d55780-8dd6-11e9-8fb7-8efc966af588.PNG)

Note that APT is attempting to install 1.6.0.0_amd64.deb and fails because its expecting ssl 1.0.0, but i have ssl 1.1.0h.

However, you can see from `dpkg -s omi` that omi 1.6.0 is already installed:

![image](https://user-images.githubusercontent.com/9218035/59450345-0b627e00-8dd7-11e9-8247-957fde466aa2.png)

**Comment by JumpingYang001** [comment] 2019-06-14 03:25
it seems a yum repo issue, @purplekrayons do you know where or what name is omi repro you installed from? As I know microsoft repro will use yum to update it.
Microsoft repro: https://docs.microsoft.com/en-us/windows-server/administration/Linux-Package-Repository-for-Microsoft-Software

**Comment by JumpingYang001** [comment] 2019-06-14 03:28
I think the issue is that there is no openssl 110 version under here: https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/o/omi/

**Comment by purplekrayons** [comment] 2019-06-14 12:39
This is the Microsoft repository I added:

```
sudo curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
```

I can confirm it's looking at the same releases you pointed out:

```
deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
```

I will also concur that the issue appears to be the missing openssl 110 versions in the Microsoft repository. Is that something you are able to address? Or is this maintained by a separate team? Are you able to engage them to resolve this?

**Comment by JumpingYang001** [comment] 2019-06-17 02:15
@purplekrayons sure, I am tracking it, will update with you once know it.

**Comment by JumpingYang001** [comment] 2019-06-18 08:39
@purplekrayons there is only 1 latest omi version package in MS repo for each platform now, it seems we cannot add 2 same version debs with different openssl version for dpkg to pickup now, and also if we do so, there might be big impact for existing Azure boxes, so I suggest you to skip upgrade omi: `sudo apt-mark hold omi` on openssl1.1.0h Ubuntu16 box and just manually install latest omi from GitHub.com.
We are thinking about how to dealt with exist openssl1.1.0 on ubuntu16, since this package isn't provided by official Ubuntu16 apt repo, it is from private built openssl1.1.0 : http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/o/openssl/ .
