### ISSUE TITLE
MI_Session needs to do http connection caching

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/omi#217] opened 2017-02-01 20:18 UTC
Currently every request goes over a fresh http connection. We need to cache connections aggressively so they are reused. This is especially important when going over the internet and doing powershell remoting to office365/exchange.

**Comment by JumpingYang001** [comment] 2017-04-09 03:26
I am interesting to fix it, but I don't know how to start with this, does store "MI_Session *session" in a static Array<MI_Session> object in Session_Create:https://github.com/Microsoft/omi/blob/master/Unix/miapi/Session.c#L166 will fit this "cache connections aggressively so they are reused", or can you give some suggestions for this? thanks very much!

**Comment by paulcallen** [comment] 2017-04-10 17:53
I am working on this issue. It requires multiple fixes to get to the final goal. I have just been busy on other things to make much progress.

**Comment by armislv** [comment] 2017-09-08 09:31
New-PSSession : [outlook.office365.com] Connecting to remote server outlook.office365.com failed with the following error message : 
MI_RESULT_FAILED For more information, see the about_Remote_Troubleshooting Help topic.

PowerShell v6.0.0-beta.6
Centos 7
but according this, it should work:
https://mattmcnabb.github.io/O365-PowerShell-On-Linux

**Comment by sarojcare** [comment] 2018-08-02 04:30
George will check with Paul and make the call.

**Comment by palladia** [comment] 2018-08-02 21:35
Discussed this with Paul.  It's technically not a bug, but an enhancement to performance when talking with PowerShell and Office365.  Closing this for now, since it's unlikely we will have resources to work on this.

**Closed by palladia** 2018-08-02 21:35 UTC
Labels: OMI Client, enhancement
