### ISSUE TITLE
Omiagent uses the entire Linux machine CPU after reboot when the machine is connected to OMS

### ISSUE THREAD

**Issue by fperez-solidq** [Microsoft/omi#297] opened 2017-04-27 18:42 UTC
We are having problems with the Linux virtual machines deployed in Azure and monitoring with OMS. When we deploy the machine and connect it to OMS, no problem, everything works. The problem comes when we restart the linux virtual machine that is connected to OMS. After the reboot the omiagent process consumes the entire CPU of the machine and sometimes the machine breaks due to lack of resources.

I have attached an image where you can see the behavior of the machine connected to OMS. The machine works well with OMS as long as it does not restart. When it restarts CPU consumption increases to 100% by the omiagent process. In the end, the CPU usage decreases because we have to kill the omiagent process.

Any suggestions? Someone has tried something to solve this "issue".

Thanks in advance
![oms-problem](https://cloud.githubusercontent.com/assets/24895358/25498850/c9f265c2-2b89-11e7-9403-f5aadbe30a3c.png)

.

**Comment by lagalbra** [comment] 2017-04-27 20:41
Related issue with more details: https://github.com/Microsoft/OMS-Agent-for-Linux/issues/398

**Comment by lagalbra** [comment] 2017-04-27 20:48
Please provide additional details:
1. Version number of the OMSAgent installed on the machine (rpm -q omi or dpkg -s omi)
2. Whether or not Docker is installed on the machine
3. Version number of the OMIAgent installed on the machine (rpm -q omi or dpkg -s omi)

**Comment by fperez-solidq** [comment] 2017-04-28 06:29
Hi again and thank for your reply!

Yes, docker is installed in the machine. I can't get the version number of the OMSAgent and OMIAgent, the commands you tell me only list directories.

Anyway, to stop the processes I had to kill them and execute the following commands:
```
wget https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent-201702-v1.3.1-15/omsagent-1.3.1-15.universal.x64.sh
sudo sh omsagent-1.3.1-15.universal.x64.sh --remove
sudo sh omsagent-1.3.1-15.universal.x64.sh --purge
```

Thanks!

**Comment by lagalbra** [comment] 2017-04-28 16:36
@keikhara and @samisms Have you seen something like this with the Docker provider before?

@fperez-solidq Please try installing the [latest agent](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/latest) on the machine that was affected to reproduce the issue. If it does not reproduce, than it may have already been fixed, but without an affected OMI/OMSAgent version number, we cannot repro the issue.

Please also provide Linux distro and version of your affected machine.

**Comment by helderpinto** [comment] 2017-06-09 14:10
I have been observing the same behaviour on one of my hosts, which also have Docker installed.
Details:
- OMS Agent: 1.3.4-127
- OMI: 1.2.0.35
- Ubuntu: Ubuntu 14.04.4 LTS
- Kernel: 3.19.0-65-generic

Had to uninstall the agent and reboot the system to get rid off the omiagent process.

**Comment by samisms** [comment] 2017-06-09 17:47
@Microsoft/omi-devs anyone seen this kind of behaviour ?

**Comment by jeffaco** [comment] 2017-06-09 18:41
Any OMI provider can cause this, and would show up as omiagent consuming a lot of CPU time.

Does this problem occur without Docker installed? If not, then the problem is likely the docker provider, and that's where the issue belongs.

Unless we have data to the contrary, I do not believe this is an OMI problem. If the problem shows up when running the OMS agent, then an issue should be opened up in the OMS repository, and the OMS folks can isolate which provider is involved and then loop in the proper group to resolve your issue.

As such, I'm closing this issue. Thanks.

**Closed by jeffaco** 2017-06-09 18:41 UTC
