### ISSUE TITLE
omicheck: missing namespace directory: root-check

### ISSUE THREAD

**Issue by stephanwib** [Microsoft/omi#364] opened 2017-08-01 12:22 UTC
Hi!

I am evaluating omiserver als well as Powershell DSC for Linux on SLES 11 and SLES 12, both amd64. I installed the rpm packages which I obtained from this site. However, when running omicheck the following error message pops up:

#./omicheck
Connecting locally to server... ok
Enumerating identify instances... ok
Checking for standard namespaces... failed
./omicheck: missing namespace directory: root-check

What is wrong here?

Thanks and regards,

Stephan

**Comment by JumpingYang001** [comment] 2017-08-02 03:00
This binary "omicheck" is only used for unit testing when building the source code, so if you use it with installing rpm/deb files in production, it will show this error. This is by design, you needn't it when you install rpm/deb packages.

**Comment by JumpingYang001** [comment] 2017-08-02 23:44
omicheck used for unittest, if we want to use in production, we need to update the code.

**Comment by JumpingYang001** [comment] 2017-08-02 23:48
If we don't want it to use for production, we should remove it from installation package.

**Comment by JumpingYang001** [comment] 2017-08-15 09:07
@jeffaco , how do you think about this?
If we want to fix the code, I can new a PR to remove unnecessary check in production in Unix/check/check.cpp.
If we want to remove it from installation package, I will new a PR to delete this line: https://github.com/Microsoft/omi/blob/c21e34d11285a122b839e6690d7a139f2aaf4272/Unix/installbuilder/datafiles/Base_OMI.data#L27 .

**Comment by jeffaco** [comment] 2017-08-15 17:50
@palladia @paulcallen Please comment if binary `omicheck` should be part of the OMI package that customers install via RPM or DPKG.

**Comment by paulcallen** [comment] 2017-08-15 19:57
this is something I am not actually familiar with. 
It is not an actual product requirement to be there (like omiserver/omicli/omiagent) , but I am not sure if it is used for validation by other products. That said, the namespace it is checking is quite odd and does not make sense.
I would probably remove the binary from the package.

**Comment by JumpingYang001** [comment] 2017-08-15 23:42
@jeffaco @paulcallen, I find there is a doc mention this usage with omi 1.0.8: http://www.admin-magazine.com/Archive/2016/32/Desired-State-Configuration-for-Linux right now

**Comment by JumpingYang001** [comment] 2017-08-15 23:49
The above link doc shows it is building the source code, so there is no problem, but from installer and in production env, it will have issue since we don't have root-check namespace in production.

**Comment by JumpingYang001** [comment] 2017-08-16 23:30
We have removed omicheck from production and fixed in #380, close this issue, thanks.

**Closed** 2017-08-16 23:31 UTC
