### ISSUE TITLE
omiagent keeps restarting

### ISSUE THREAD

**Issue by sbadakhc** [Microsoft/omi#381] opened 2017-08-16 21:23 UTC
Hi, I have issued the following command to stop the agent
```
/opt/omi/bin/service_control stop
```
But I after a few seconds I see the agent has started again. I need to stop the agent until we can find out why its eating so much CPU and RAM. Please advise. Thanks in advance.

**Comment by JumpingYang001** [comment] 2017-08-16 22:59
looks like omi service has a restart mechanism when it is stopped.
When the omiserver process started, any query request will make same/different omiagent started.

We have an issue about omiagent 100% CPU #358, but I don't have Azure to repro it, could you help to check your omi version? `rpm -qa|grep omi` or `dpkg -l|grep omi`

if you meet the 100% CPU issue next time, you can dumpcore with gcore -o omiagent.core <pid of omiagent process with 100% CPU> (Need gdb:apt-get install gdb) which will generate a file omiagent.core.pid under your current path and send it to my email: yzpcreate@qq.com, thanks.

**Comment by JumpingYang001** [comment] 2017-08-16 23:05
This command will stop omiserver process:
`/opt/omi/bin/service_control stop`
Does the omiserver start again after you run above command?
Check omiserver process still live: `ps -aux|grep omiserver`

**Comment by JumpingYang001** [comment] 2017-08-16 23:20
If `/opt/omi/bin/service_control stop` doesn't stop omiserver process when high CPU, you need to kill it manually: `kill -9 `ps -ef|grep omiserver|grep -v 'grep'|awk '{print $2}'``, thanks.

**Comment by sbadakhc** [comment] 2017-08-16 23:58
I'm happy to help. I will post the here tomorrow as its way past my bed time. Thanks for the help!

**Comment by sbadakhc** [comment] 2017-08-17 17:36
Hi,
I have not seen omiagent hit a 100% but I still cannot kill the process as it keeps starting up. We also started seeing the mdsd daemon eat up cpu. The load on the nodes went above 7.00.

**Comment by JumpingYang001** [comment] 2017-08-17 23:41
hey @sbadakhc, if omiagent is always restarting it may be by design, because once the query send to omiserver, omiagent will dealt with it and omiagent will shutdown once it is complete the query processing.

I don't know what is mdsd daemon.

`/opt/omi/bin/service_control stop` will stop omiserver process, it also will stop omiagent process once omiserver is shutdown.

so what's your issue?
1. `/opt/omi/bin/service_control stop`  doesn't work, because omiagent will still keep restart?
2. omiagent eat high CPU?

for issue 1, could you check omiserver is really stop(`ps -aux|grep omiserver`) after you run `/opt/omi/bin/service_control stop` ?

and what's your environment like Ubuntu16.04x64 on Azure Docker Host?
and what's your omi version? `rpm -qa|grep omi or dpkg -l|grep om`

for issue 2, you can give me the gcore file, I will analysis it.

**Comment by paulcallen** [comment] 2017-08-17 23:50
if you have docker on your machine it is possibly an old docker provider that is causing the omiagent provider problem. I believe it has been fixed , and if this is an azure machine I believe they are trying to work out an update for this. I am not sure the status of this though.
If you don't have docker then you may need to dig a little deeper. Attaching a debugger to the agent process should free up your CPU though.

**Comment by sbadakhc** [comment] 2017-08-18 10:04
Thanks for the update. We have docker installed and its possible that it is an old version as we deploy on RHEL. Do you know which docker version is affected? We have managed to mitigate the problem by stop omsagent and mdsd which has rendered omiagent impotent.

**Comment by sbadakhc** [comment] 2017-08-18 10:36
Just for reference I kill both the omiserver and agent with the following command:
``
sudo kill -9 $(ps -ef | grep omi* | grep -v 'grep'|awk '{print $2}')
```
But they both pop back up in a few seconds.

**Comment by JumpingYang001** [comment] 2017-08-18 11:02
@sbadakhc, to approve who start up omiserver, you can try:
stop oms and then stop omiserver to check if it up again?
- If so, then omiserver itself restart.
- If omiserver never up again, then oms start the omiserver.

I am not familiar with mdsd, looks like it is https://github.com/Azure/fluentd-plugin-mdsd ?

oms will have a docker-provider which call omiserver to launch omiagent if your vm installed docker, docker-provider is here: https://github.com/Microsoft/Docker-Provider

**Comment by sbadakhc** [comment] 2017-08-18 13:53
Great, thanks again for the help. I will keep an eye on it and see how it goes.

**Comment by JumpingYang001** [comment] 2017-09-23 05:10
Good news: I have got the gdb core file from one customer, they are getting the 100% CPU issue for the omiagent on our Azure hosted docker/swarm environment.
The problem is on docker-provider side.

omi:
  Installed: 1.3.0.2

Debugging information:
```
gdb /opt/omi/bin/omiagent omiagent.core.30992
#0  0x00007f521c860bae in do_xfrm_cached (rulearr=<optimized out>, idxarr=<optimized out>, idxmax=<optimized out>, l_data=<optimized out>, n=<optimized out>, dest=<optimized out>)
    at strxfrm_l.c:462
462     strxfrm_l.c: No such file or directory.
(gdb) bt
#0  0x00007f521c860bae in do_xfrm_cached (rulearr=<optimized out>, idxarr=<optimized out>, idxmax=<optimized out>, l_data=<optimized out>, n=<optimized out>, dest=<optimized out>)
    at strxfrm_l.c:462
#1  __GI___strxfrm_l (
    dest=0x240c998 "GET /containers/3b07a6f60314b750a7ba66355365491d9248d2cd2b3c9a674996ac9660968b2e/logs?stderr=1&stdout=1&since=1501945087&timestamps=1 HTTP/1.1\r\nHost: localhost\r\n\r\n", src=<optimized out>, n=2319406722901352496, l=<optimized out>) at strxfrm_l.c:739
#2  0x00007f521c37596f in mi::ContainerLogQuery::QueryAll() () from /opt/omi/lib/libcontainer.so
#3  0x00007f521c374b83 in mi::Container_ContainerLog_Class_Provider::EnumerateInstances(mi::Context&, mi::String const&, mi::PropertySet const&, bool, _MI_Filter const*) ()
   from /opt/omi/lib/libcontainer.so
#4  0x00007f521c37ea1e in Container_ContainerLog_EnumerateInstances () from /opt/omi/lib/libcontainer.so
#5  0x0000000000407a30 in ProvMgr_NewRequest ()
#6  0x00000000004045b6 in _RequestCallback ()
#7  0x00000000004619d2 in _ConnectionIn_Post ()
#8  0x000000000045df37 in _StrandMethod_Parent_Post ()
#9  0x000000000045bfe3 in _Strand_ExecuteLoop ()
#10 0x00000000004471d2 in _ProtocolSocket_Aux_PostMsg ()
#11 0x000000000045ad6b in _StrandMethod_Aux0 ()
#12 0x000000000045bfe3 in _Strand_ExecuteLoop ()
#13 0x0000000000447a3f in _ProcessReceivedMessage ()
#14 0x0000000000448170 in _RequestCallback ()
#15 0x0000000000463bed in Selector_Run ()
#16 0x0000000000404c29 in agent_main ()
#17 0x00007f521c7e7f45 in internal_ucs4_loop_single (irreversible=<optimized out>, outend=<optimized out>, outptrp=<optimized out>, inend=<optimized out>, inptrp=<optimized out>, 
    step_data=<optimized out>, step=<optimized out>) at gconv_simple.c:187
#18 __gconv_transform_internal_ucs4 (step=0x8ffffff98, data=0x0, inptrp=0x7ffec430ead0, inend=0x22 <error: Cannot access memory at address 0x22>, outbufstart=0x201, irreversible=0x0, 
    do_flush=-1003427112, consume_incomplete=9) at ../iconv/skeleton.c:563
#19 0x00000000004811e0 in ?? ()
#20 0x00007ffec430ead8 in ?? ()
#21 0x0000000000000009 in ?? ()
#22 0x0000000000000000 in ?? ()
```

**Comment by JumpingYang001** [comment] 2017-09-23 05:28
@sbadakhc, omiagent is called by others like omsagent or other providers(scx or dockerprovider), omiagent should shutdown once omiserver is down, if omiserver doesn't exist, omiagent will never be called up by omiserver, so this is not omi issue, it should be omi caller's issue, I want to close this issue, thanks.
For OMI caller:
OMS: https://github.com/Microsoft/OMS-Agent-for-Linux
Docker-Provider:https://github.com/Microsoft/Docker-Provider
SCXcore:https://github.com/Microsoft/scxcore

**Closed by JumpingYang001** 2017-09-23 05:28 UTC

**Comment by JumpingYang001** [comment] 2017-09-23 05:41
Linked to https://github.com/Microsoft/Docker-Provider/issues/32, so anyone check this issue will go there to track, thanks.

**Comment by sbadakhc** [comment] 2017-10-11 12:54
Thanks for he heads up. I will schedule a time to test and get back to you,
