### ISSUE TITLE
Why it is automatically installed on my VM?

### ISSUE THREAD

**Issue by Sraw** [microsoft/omi#642] opened 2019-08-20 08:02 UTC
I've searched a lot but without any luck. I can confirm that I have never manually installed it. But it just shows on my VM. So I have the following questions:

1. Why it is automatically installed? In what kind of situations?
2. Is it safe to delete it?
3. There is a crontab task runs every minute, what does it do? `* * * * * [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab`

Thanks in advance!

**Comment by JumpingYang001** [comment] 2019-08-26 09:10
@Sraw it is a cron job for Kerberos authentication in omi, if you don't use Kerberos authentication or you don't want Kerberos to authentication with omi, we have provided a way to purge omi Kerberos setting started in omi 1.6.0 :
```
sudo /opt/omi/bin/support/config_keytab_update.sh --purgeforever
sudo rm -rf /etc/opt/omi/creds/omi.keytab
sudo /opt/omi/bin/service_control restart
```
By default, it used Basic authentication for remoting and binary protocol for local communication between omiserver/omiengine and omicli.

It is installed by default when installing omi, and omi will be installed by OMS/LAD on Azure.

**Closed by JumpingYang001** 2019-08-26 09:10 UTC

**Comment by Sraw** [comment] 2019-08-26 09:27
Thanks for all your information, really helpful!

**Comment by syed316** [comment] 2022-06-21 16:38
@JumpingYang001  Today we have updated the OMI package (1.6.9.1) in ubuntu 20.04.4 LTS, which made Root's crontab entry change and found the cron expression as follows
* * * * * [ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && sleep 5 && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab >/dev/null 2>&1 || true.

We have updated the OMI 1.6.9.1 on multiple servers, however, only one server got this Root crontab, please help us with what could be the reason or root cause.

**Comment by JumpingYang001** [comment] 2022-06-22 01:40
@syed316 I guess:
1. you have `/etc/.omi_keytabcron_purge_forever` on the no crontab entry box.
2. you don't have `cron` or `crond` process started when installing omi, and it will no crontab entry.
