### ISSUE TITLE
OMI package fails to install on SLES 15 SP6 having OpenSSL version 3.1.4

### ISSUE THREAD

**Issue by GulhaneChaitanya** [microsoft/omi#765] opened 2024-05-27 07:37 UTC
Hi,

We observed an issue that OMI package version - omi-1.9.0-0.ssl_300.ulinux.s.x64.rpm fails to install with OpenSSL 3.1.4 on SLES 15 SP 6

localhost:~ # openssl version
OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)
localhost:~ #
localhost:~ # rpm -ivh omi-1.9.0-0.ssl_300.ulinux.s.x64.rpm
warning: omi-1.9.0-0.ssl_300.ulinux.s.x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
Preparing...                          ################################# [100%]
Preinstall script error: Unrecognized version of SSL on the system: 3.1.4
error: %prein(omi-1.9.0-0.x86_64) scriptlet failed, exit status 2
error: omi-1.9.0-0.x86_64: install failed

Could you please let us know the resolution if any?

Regards,
Chaitanya.

**Comment by JumpingYang001** [comment] 2024-05-28 09:24
@GulhaneChaitanya currently, only support openssl 3.0.x.

**Comment by GulhaneChaitanya** [comment] 2024-05-28 09:32
@JumpingYang001 - Could you please let us know when can we expect the support for OpenSSL 3.1.4?

**Comment by JumpingYang001** [comment] 2024-05-28 09:42
@GulhaneChaitanya I don't know the plan at present, will share with you once I know.

**Comment by JumpingYang001** [comment] 2024-06-04 09:28
@GulhaneChaitanya update: it will be in next release.

**Comment by greeneg** [comment] 2024-06-30 04:24
Is there an estimation of when the next release will be made available?

**Comment by JumpingYang001** [comment] 2024-07-15 05:59
I don't know when next release come, will update here if I know, thanks.

**Comment by deamn** [comment] 2024-07-16 08:38
A quick release will be appreciate

**Comment by roelandjansen** [comment] 2024-08-05 07:43
We also face this issue. As the documentation states that SLES15 is supported I would have thought that this would work. 
But indeed 3.1.4 is too new.

**Comment by marsbeetle** [comment] 2024-08-19 11:10
3+ months since the public release of a supported Operating System and still no support for OpenSSL 3.1 ?

**Comment by JumpingYang001** [comment] 2024-09-20 08:59
new release:
https://github.com/microsoft/omi/releases/tag/v1.9.1-0
https://github.com/microsoft/SCXcore/releases/tag/v1.9.1-0

**Closed by JumpingYang001** 2024-09-20 08:59 UTC

**Comment by beckjkl** [comment] 2024-10-29 10:46
The issue is not resolved:
`SERVERNAME:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP6"
VERSION_ID="15.6"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP6"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp6"
DOCUMENTATION_URL="https://documentation.suse.com/"
SERVERNAME:~ # zypper install omi
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following package is going to be upgraded:
  omi

The following package has no support information from its vendor:
  omi

1 package to upgrade.
Overall download size: 0 B. Already cached: 1.9 MiB. After the operation, 2.0 B will be freed.

Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y): y
In cache omi-1.9.1-0.x86_64.rpm                                                                                                       (1/1),   1.9 MiB

Checking for file conflicts: .......................................................................................................................[done]
Expecting SSL version (compatible with): 1.1.0
SSL version found on system:             3.1.4
Incorrect version of OMI for your system, please check SSL version.
error: %prein(omi-1.9.1-0.x86_64) scriptlet failed, exit status 3
error: omi-1.9.1-0.x86_64: install failed
error: omi-1.9.0-0.x86_64: erase skipped
(1/1) Installing: omi-1.9.1-0.x86_64 ..............................................................................................................[error]
Installation of omi-1.9.1-0.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: Command exited with status 1.
Abort, retry, ignore? [a/r/i] (a): a
Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
Please see the above error message for a hint.`

**Comment by roelandjansen** [comment] 2024-10-29 17:54
[azure-packages]
enabled=1
autorefresh=1
baseurl=https://packages.microsoft.com/sles/15/sles15-sp6/

is the repo file. Your problem is that you might have a cached wrong version (e.g. the old version that failed)

see: 

"In cache omi-1.9.1-0.x86_64.rpm (1/1), 1.9 MiB"

so you need to clean your cache, refresh the repo(s) and then it will work.

**Comment by marsbeetle** [comment] 2024-10-30 06:57
@beckjkl  ...you can also try:

```
localhost:/tmp # wget https://github.com/microsoft/omi/releases/download/v1.9.1-0/omi-1.9.1-0.ssl_300.ulinux.s.x64.rpm
localhost:/tmp # rpm -Uvh ./omi-1.9.1-0.ssl_300.ulinux.s.x64.rpm
```

The script for the package will take care of the upgrade.

**Comment by roelandjansen** [comment] 2024-11-09 12:10
@marsbeetle 


it's always better for LCM and security to not do that. Use the repo whenever possible.
