### ISSUE TITLE
OMI server crashes with "Error BatchSize while reading header"

### ISSUE THREAD

**Issue by rashmichandrashekar** [Microsoft/omi#542] opened 2018-07-10 23:52 UTC
I am seeing the following error in the omiserver.log while sending data from the provider. 
EventId=30128 Priority=WARNING (E)Socket: 0xd5aea0, Error BatchSize while reading header
The omi version is :
**/opt/omi/bin/omiserver: OMI-1.4.2-2 - Mon Mar 19 10:19:49 PDT 2018**

I have attached the omiagent and server logs.
[omiagent.root.root.log](https://github.com/Microsoft/omi/files/2182475/omiagent.root.root.log)
[omiserver.log](https://github.com/Microsoft/omi/files/2182476/omiserver.log)

We have some providers that are getting containers using docker ps. But not all containers are showing up in the OMS workspace. This is the error I found in the logs. Please let me know if you need more information.
The class that is having trouble is **Container_ContainerInventory**

**Comment by rashmichandrashekar** [comment] 2018-07-10 23:57
@JumpingYang001 : Since you helped with another issue regarding socket error, do you have any insights on this issue?
https://github.com/Microsoft/omi/issues/536

**Comment by JumpingYang001** [comment] 2018-07-11 02:51
checking...

**Comment by JumpingYang001** [comment] 2018-07-11 03:12
@rashmichandrashekar omiserver got a header greater than MAX_ENVELOPE_SIZE and get "Error BatchSize while reading header": https://github.com/Microsoft/omi/blob/39304cdea0e8a28845614097cb3cf2d5b0438bde/Unix/protocol/protocol.c#L2157

[Unix/common/common.h](https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/common/common.h#L43)
```
Showing the top match Last indexed on Jan 19
 // Following will be used to limit the buffere size server can accept from provider host.
// This is also used to limit the max size on http transport
#define MAX_ENVELOPE_SIZE   (250*1024)
```
I think you should check why Container_ContainerInventory header is greater than MAX_ENVELOPE_SIZE
**Tip:**
once enable logging in `/etc/opt/omi/conf/omiserver.conf` and `/etc/opt/omi/conf/omicli.conf`, you will see `/var/opt/omi/log/omiclient-send.trc` which should contains the header information.

**Comment by rashmichandrashekar** [comment] 2018-07-11 07:33
Thanks @JumpingYang001. I enabled loglevel = DEBUG/ loglevel = INFO and restarted the omi service using:
sudo /opt/omi/bin/service_control stop
sudo /opt/omi/bin/service_control start
But I dont see the log file omiclient-send.trc under /var/opt/omi/log/.
Am I missing something?

**Comment by JumpingYang001** [comment] 2018-07-11 07:42
@rashmichandrashekar maybe you need to query Container_ContainerInventory .

**Comment by JumpingYang001** [comment] 2018-07-11 07:44
try `/opt/omi/bin/omicli ei root/cimv2 Container_ContainerInventory`

**Comment by palladia** [comment] 2018-07-11 16:17
Although I don’t know why 250K was chosen as the header size limit, but that’s already rather large, and it seems most likely that the client did not build the packet correctly.

**Comment by vishiy** [comment] 2018-07-11 21:38
@rashmichandrashekar - May be we can batch from our side ?

**Comment by rashmichandrashekar** [comment] 2018-07-11 22:55
@JumpingYang001 @palladia : I have attached the miclient.log file. This is the log that was created once I tried: /opt/omi/bin/omicli ei root/cimv2 Container_ContainerInventory.
But this only tells me that MI_RESULT_FAILED.
How do I find out what part of the header is causing the problem? 
[miclient.log](https://github.com/Microsoft/omi/files/2186467/miclient.log)

**Comment by JumpingYang001** [comment] 2018-07-11 23:36
see `/var/opt/omi/log/omiclient-send.trc ` instead of miclient.log to check the header content.

**Comment by JumpingYang001** [comment] 2018-07-12 04:18
try add "httptrace=true" in omiserver.conf then restart omi, you'll see `/var/opt/omi/log/omiclient-send.trc` while invoking `/opt/omi/bin/omicli ei root/cimv2 Container_ContainerInventory`

omiserver usage:
```
# /opt/omi-1.0.8/bin/omiserver -h
Usage: /opt/omi-1.0.8/bin/omiserver [OPTIONS]

This program starts the server.

OPTIONS:
    -h, --help                  Print this help message.
    -d                          Daemonize the server process (POSIX only).
    -s                          Stop the server process (POSIX only).
    -r                          Re-read configuration by the running server (POSIX only).
    --reload-dispatcher         Re-read configuration by the running server (POSIX only), but don't unload providers.
    --httpport PORT             HTTP protocol listener port.
    --httpsport PORT            HTTPS protocol listener port.
    --idletimeout TIMEOUT       Idle providers unload timeout (in seconds).
    -v, --version               Print version information.
    -l, --logstderr             Send log output to standard error.
    --loglevel LEVEL            Set logging level to one of the following
                                symbols/numbers: fatal/0, error/1, warning/2,
                                info/3, debug/4, verbose/5 (default 2).
    --httptrace                 Enable logging of HTTP traffic.
    --timestamp                 Print timestamp server was built with.
    --nonroot                   Run in non-root mode.
    --service ACCT              Use ACCT as the service account.

```

**Comment by JumpingYang001** [comment] 2018-07-12 05:45
when invoking local, omi use binary protocol, so it don't have httptrace log.
we need remoting to local to check the issue, so we need to set "httpsport=0,5985" in omiserver.conf, then `/opt/omi/bin/service_control restart` to enable 5985 port for affection, then run `/opt/omi/bin/omicli  ei root/cimv2 Container_ContainerInventory -u yourusername -p 'yourpassword' --auth Basic --hostname localhost --port 5986 --encryption https`. Then you'll see the .trc files under `/var/opt/omi/log/`.

As I know, your querying are running in omsagent account, so omsagent is yourusername, but other accounts may also be ok, I am not very sure.

**Comment by JumpingYang001** [comment] 2018-07-16 03:15
As discussed offline, we have found the container provider's Container_ContainerInventory packet is more than the max limit 250kb, and after fixing it in container code to make it less 250kb, the problem is resolved, so close the issue, thanks.

**Closed by JumpingYang001** 2018-07-16 03:15 UTC
