### ISSUE TITLE
Cron job errors

### ISSUE THREAD

**Issue by moijafcor** [Microsoft/omi#425] opened 2017-11-01 11:22 UTC
After apt upgrade two of my Ubuntu Servers (Ubuntu 16.04.3) VM on Azure this morning, cron is mailing the following errors:

Subject:
Cron <root@HOSTNAME> [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab 

Body:
src kt = /etc/krb5.keytab /opt/omi/bin/support/ktstrip: 57: /opt/omi/bin/support/ktstrip: ktutil: not found Creating /etc/opt/omi/creds/omi.keytab /opt/omi/bin/support/ktstrip: 73: /opt/omi/bin/support/ktstrip: ktutil: not found Move /tmp/tmp.kt to /etc/opt/omi/creds/omi.keytab mv: cannot stat ‘/tmp/tmp.kt’: No such file or directory chown: cannot access ‘/etc/opt/omi/creds/omi.keytab’: No such file or directory could not set user omi:omi as owner of /etc/opt/omi/creds/omi.keytab /opt/omi/bin/support/ktstrip: 82: exit: Illegal number: -1

**Comment by JumpingYang001** [comment] 2017-11-06 08:55
@yakman2020 @palladia, this is due to no Kerberos installed on the machine, is it by design?

**Comment by mstrhh** [comment] 2017-12-19 09:30
Same problem here on RHEL 7.4 after upgrading omi from  omi-1.2.0 to 1.4.1 .

Because the cron error was mailed every minute I did `touch /etc/krb5.keytab`.
This gave the following messages once:
```
src kt = /etc/krb5.keytab
/opt/omi/bin/support/ktstrip: line 57: ktutil: command not found Creating /etc/opt/omi/creds/omi.keytab
/opt/omi/bin/support/ktstrip: line 73: ktutil: command not found Move /tmp/tmp.kt to /etc/opt/omi/creds/omi.keytab
mv: cannot stat ‘/tmp/tmp.kt’: No such file or directory
chown: cannot access ‘/etc/opt/omi/creds/omi.keytab’: No such file or directory
could not set user   omi:omi  as owner of /etc/opt/omi/creds/omi.keytab
```
The question is: is this now fixed?

**Comment by JumpingYang001** [comment] 2017-12-19 09:35
@mstrhh ,it is fixing on #468 .

**Comment by mstrhh** [comment] 2017-12-19 09:45
@JumpingYang001 so an empty keytab is sufficient I conclude. Thanks for the quick reaction.

**Comment by JumpingYang001** [comment] 2017-12-19 22:51
@mstrhh, you needn't/shouldn't touch an empty keytab, just remove the omi.keytab line in cron since you don't use Kerberos authentication.

**Comment by silverl** [comment] 2018-01-25 15:28
What is the kerberos authentication being used for? Why is commenting out the cron line acceptable? Does this affect functionality?

Also, won't the cron line be put back in place the next time OMI is updated?

**Comment by onedotover** [comment] 2018-01-25 17:22
This just started randomly for us last night. I have the same question as @silverl. Is this something that needs to be looked into? I ran `/opt/omi/bin/support/config_keytab_update.sh --unconfigure` to disable it for now but I'm not sure if there is a bigger issue that needs to be addressed.

**Comment by paulmalyn** [comment] 2018-01-25 17:54
This also started for us this morning. Started getting emails every minute from 06:16 GMT. I too have disabled it but would love to know why this started and if it is an issue that needs to be resolved.

**Comment by mcbsys** [comment] 2018-01-25 17:59
This suddenly started up at 10:17pm PST last night. One error per minute, each one sent as an email, 680+ emails this morning. This is a Bitnami stack WordPress server on Azure.

Subject
Cron <root@PBUMCWEB> [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab 

Body
src kt = /etc/krb5.keytab
File   /etc/krb5.keytab  does not exist
/opt/omi/bin/support/ktstrip: 38: exit: Illegal number: -1

There is no /etc/opt/omi/creds/omi.keytab file.

I see that /var/spool/cron/crontabs/root was changed last night at 10:16:35pm, apparently adding the line to call omi.keytab. I sure didn't add it--I don't even know what OMI is or why it is included/needed on this server. Wondering if Microsoft is pushing this cron change onto Azure guests? @onedotover, @paulmalyn, are your servers on Azure?

**Comment by onedotover** [comment] 2018-01-25 18:04
Yes, we are on Azure and we did not add this line to our crontab either. Interestingly, this is one of several VMs we have on Azure and was the only one with the issue.

**Comment by mcbsys** [comment] 2018-01-25 18:06
I have another Bitnami Wordpress web server on Azure as well but it doesn't have OMI installed at all, which is why I'm wondering what OMI is and why it is there. @onedotover, do your other servers even have OMI?

**Comment by paulmalyn** [comment] 2018-01-25 18:07
Yes I have 2 identical linux VMs on Azure but only one started doing this. Both appear to have OMI installed, but until this happened I didn't even know it was there.

**Comment by onedotover** [comment] 2018-01-25 18:10
Yes, it looks like all of our VMs have OMI installed on them. Is it included in the images provided by Azure? We didn't install it. I'm not sure if/how it is used by Azure or the portal.

**Comment by mcbsys** [comment] 2018-01-25 18:40
It'd be nice to know if Microsoft or Omi is doing some auto-update to our machines. It would require root privileges to change the root crontab.

It took me awhile to find this Github bug report. I've blogged the issue with reference back here:

https://www.mcbsys.com/blog/2018/01/omi-keytab-errors-suddenly-start-on-azure-server/

**Comment by directhex** [comment] 2018-01-25 21:49
The fix is in https://github.com/Microsoft/omi/commit/7a8ac63c4c58d8aa327a1122312d938b367e694d but not in any tagged release

For unfathomable reasons, the faulty version was force-pushed last night.

**Comment by EricTendian** [comment] 2018-01-25 22:44
I had this happen to a few of my VMs as well, with the cron job running at 06:16:01 GMT. In addition to the cron job causing lots of emails, the CPU for some of the VMs which received the update (not all of them) went to 100% about 10 seconds before because of the mdsd process (mdsd-lde service) - see https://social.msdn.microsoft.com/Forums/azure/en-US/5ab85f9b-0bfc-482f-8331-bbd7d994e1c2/high-cpu-usage-by-mdsd-command-in-azure-linux-vm?forum=WAVirtualMachinesforWindows for more info on that.

Whatever happened seems to be bigger than just a cron job failing, as other effects were triggered from the extension update.

Here's what it looked like from a system resources perspective:

![screenshot from 2018-01-25 16-40-24](https://user-images.githubusercontent.com/498525/35416371-87e5daa6-01ee-11e8-9d79-052740908d3f.png)

And a snippet of syslogs:

```
Jan 25 06:15:30 {redacted} python3[1180]: 2018/01/25 06:15:30.341189 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Target handler state: enabled
Jan 25 06:15:30 {redacted} python3[1180]: 2018/01/25 06:15:30.349937 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] [Enable] current handler state is: notinstalled
Jan 25 06:15:35 {redacted} python3[1180]: 2018/01/25 06:15:35.874452 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=Download succeeded, duration=0
Jan 25 06:15:35 {redacted} python3[1180]: 2018/01/25 06:15:35.890790 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:35 {redacted} python3[1180]: 2018/01/25 06:15:35.902593 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Initialize extension directory
Jan 25 06:15:36 {redacted} python3[1180]: 2018/01/25 06:15:36.038708 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update settings file: 0.settings
Jan 25 06:15:36 {redacted} python3[1180]: 2018/01/25 06:15:36.054356 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Disable extension [omsagent.py -disable]
Jan 25 06:15:36 {redacted} systemd[1]: Stopping Operations Management Suite agent...
Jan 25 06:15:36 {redacted} systemd[1]: omsagent-{redacted}.service: Main process exited, code=killed, status=9/KILL
Jan 25 06:15:36 {redacted} systemd[1]: Stopped Operations Management Suite agent.
Jan 25 06:15:36 {redacted} systemd[1]: omsagent-{redacted}.service: Unit entered failed state.
Jan 25 06:15:36 {redacted} systemd[1]: omsagent-{redacted}.service: Failed with result 'signal'.
Jan 25 06:15:36 {redacted} systemd[1]: Reloading.
Jan 25 06:15:36 {redacted} systemd[1]: Starting Daily apt upgrade and clean activities...
Jan 25 06:15:36 {redacted} systemd[1]: Started ACPI event daemon.
Jan 25 06:15:36 {redacted} systemd[1]: Reloading.
Jan 25 06:15:36 {redacted} systemd[1]: Started ACPI event daemon.
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.072793 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Disable, message=Launch command succeeded: omsagent.py -disable, duration=0
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.096212 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.107894 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Copy status files from old plugin to new
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.121501 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update extension [omsagent.py -update]
Jan 25 06:15:38 {redacted} python3[1180]: 2018/01/25 06:15:38.140972 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Update, message=Launch command succeeded: omsagent.py -update, duration=0
Jan 25 06:15:38 {redacted} python3[1180]: 2018/01/25 06:15:38.157980 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:38 {redacted} python3[1180]: 2018/01/25 06:15:38.169870 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Uninstall extension [omsagent.py -uninstall]
Jan 25 06:15:38 {redacted} systemd[1]: Stopping OMI CIM Server...
Jan 25 06:15:38 {redacted} omiserver[430]: /opt/omi/bin/omiserver: stopped server
Jan 25 06:15:38 {redacted} systemd[1]: Stopped OMI CIM Server.
Jan 25 06:15:38 {redacted} systemd[1]: Starting OMI CIM Server...
Jan 25 06:15:38 {redacted} systemd[1]: omid.service: PID file /var/opt/omi/run/omiserver.pid not readable (yet?) after start: No such file or directory
Jan 25 06:15:38 {redacted} systemd[1]: Started OMI CIM Server.
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.186971 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=UnInstall, message=Launch command succeeded: omsagent.py -uninstall, duration=0
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.201603 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.212578 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Remove extension handler directory: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.248443 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Install extension [omsagent.py -install]
```

**Comment by JumpingYang001** [comment] 2018-01-25 23:53
@silverl, Kerberos authentication:https://en.m.wikipedia.org/wiki/Kerberos_(protocol)
omi support this feature, and it need use keytab when machine are enabled Kerberos.
this bug has fixed in #468 and merged to master, but the release version with it will come later.

**Comment by JumpingYang001** [comment] 2018-01-26 00:00
@onedotover @paulmalyn @mcbsys @directhex @EricTendian Azure is using omi might be that you  are enabling OMS or Linux Diagnostic extension.
OMS: https://github.com/Microsoft/OMS-Agent-for-Linux
Linux Diagnostic extension: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/diagnostic-extension

**Comment by JumpingYang001** [comment] 2018-01-26 00:04
@EricTendian Looks mdsd is using by oms, if you are using oms, you can go to OMS: https://github.com/Microsoft/OMS-Agent-for-Linux to report your issue, thanks.

**Comment by mcbsys** [comment] 2018-01-26 01:27
Thank you @JumpingYang001. Yes, I see the affected machine has both the LinuxDiagnostic 2.* extension and the OmsAgentForLinux 1.* extension installed.

Can you or perhaps @directhex explain how/why "For unfathomable reasons, the faulty version was force-pushed last night." Is this "force push" part of automatic minor-version updates? Can you force-push a fix?

**Comment by jeffaco** [comment] 2018-01-26 01:43
OMI is a component that's used to collect system statistics for machines in Azure.

The fix in question, https://github.com/Microsoft/omi/commit/7a8ac63c4c58d8aa327a1122312d938b367e694d, is currently being tested with our test team for OMI v1.4.2-0. We can't release that yet as it hasn't completed a test pass.

We believe this occurred because a new version of OMS was pushed out without this fix (as I said, v1.4.2-0 wasn't ready yet). Unfortunately, we were unaware that v1.4.1-0 behaved in this way. Had we known that, we obviously wouldn't have allowed OMS to ship OMI with that bug.

We are looking at this closely and hope to have something the Azure team can push out shortly.

**Comment by stuarthts** [comment] 2018-01-26 16:20
Since 1am last night, I am receiving an email every minute saying the following:

src kt = /etc/krb5.keytab
File   /etc/krb5.keytab  does not exist
/opt/omi/bin/support/ktstrip: 38: exit: Illegal number: -1

VM is hosted in Azure. Is this something they would have done and is there a fix coming for this? @JumpingYang001

**Comment by directhex** [comment] 2018-01-26 16:28
@stuarthts this affects all Linux VMs on Azure with diagnostic services enabled. The workaround is to run `sudo /opt/omi/bin/support/config_keytab_update.sh --unconfigure` and the fix is already done - but not yet shipped.

**Comment by stuarthts** [comment] 2018-01-26 16:33
thanks @directhex Is there a timeline as to when the fix will be automatically applied?

**Comment by directhex** [comment] 2018-01-26 16:46
There are multiple teams involved in pushing out the fix, but relevant managers are discussing an expedited hotfix on a short timeline, rather than waiting for the fix to be included as part of the next service release

**Comment by stuarthts** [comment] 2018-01-29 19:29
Any updates on this?

**Comment by JumpingYang001** [comment] 2018-01-29 22:18
@stuarthts , OMI team published the hot fixes on https://github.com/Microsoft/omi/releases/tag/v1.4.1-1, OMS team should publish the hot fixes on Azure later.
@all,  if  you  tried to touch /etc/krb5.keytab, please remove it! thank you!

**Comment by jeffaco** [comment] 2018-01-29 23:57
@stuarthts We've pushed a new version of OMI [here](https://github.com/Microsoft/omi/releases/tag/v1.4.1-1). This is still undergoing testing. If you wish, you can install that, and it should fix your problem (please let us know one way or the other).

We're working on this internally to get mitigation instructions in place for customers impacted by this.

**Comment by JumpingYang001** [comment] 2018-01-30 23:06
@onedotover @paulmalyn @mcbsys @directhex @EricTendian Hi all, I setup an Azure CentOS7.4 today and I doesn't receive any email Even I can see send mails log in /var/log/maillog, I want to know if you configure email for cron or set your email ~/.forward, could you help to describe how you set the email sending by cron? so I can understand more about your environments, thanks very much!

**Comment by mcbsys** [comment] 2018-01-30 23:47
@JumpingYang001, I'm using a Bitnami stack that includes Apache and WordPress. I think it's based on Ubuntu. I installed sSMTP to send emails. I've used Office 365 and Gmail accounts (you probably have to allow "less secure" senders for Gmail). I see from searching that others use SendGrid. All of these are ways to send email through an authenticated account--I don't know if it is even possible on Azure to open outbound port 25 and send directly from sendmail--that is what spammers would like to do so they may block that.

**Comment by JumpingYang001** [comment] 2018-01-30 23:57
@mcbsys , thanks for help! that's very useful for me!

**Comment by directhex** [comment] 2018-01-31 01:00
I'm using SendGrid (configured via Azure, you get loads of free messages), and have Postfix configured on Ubuntu server. This is useful, as it means all mail generated by root can go to my work address, and alert me to issues.

**Comment by jeffaco** [comment] 2018-01-31 01:13
@directhex Can you try installing OMI v1.4.1-1 from [here](https://github.com/Microsoft/omi/releases/tag/v1.4.1-1). I'd like confirmation that this fixes your problem with E-Mail message. Thanks!

**Comment by directhex** [comment] 2018-01-31 17:02
@jeffaco seems to handle the specific problem case fine:

```bash
root@jenkins-master-2:~# ls -l /etc/krb5.keytab
ls: cannot access /etc/krb5.keytab: No such file or directory
root@jenkins-master-2:~# [ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab || true
root@jenkins-master-2:~# 
```

Nothing in the mail queue.

**Comment by jeffaco** [comment] 2018-01-31 17:06
@directhex Awesome, Jo. Thanks for helping us out here!

We're (still) working on this internally to get mitigation instructions in place for customers impacted by this. We should get back soon, sorry again for the delay.

**Comment by mstrhh** [comment] 2018-01-31 19:04
@JumpingYang001 configuring MAILTO= in /etc/crontab caused the mail flood about the failing job in my case.

**Comment by JumpingYang001** [comment] 2018-01-31 22:53
@mstrhh , thanks for help! Now I know most of ways for cron mailing.

**Comment by symgryph** [comment] 2018-02-02 00:01
Add me to the list. Why in heavens name did you do this? At least send output to 2>&1 /dev/null?????

**Comment by JumpingYang001** [comment] 2018-02-02 00:22
@symgryph , sorry for this issue, we will take carefully in the future.

**Comment by palladia** [comment] 2018-02-14 17:46
A fix for this problem is available in omi-1.4.2-1.

**Closed by palladia** 2018-02-14 17:46 UTC

**Comment by morgzz** [comment] 2018-03-15 14:07
This issue generated 16,599 spam error emails over the course of 3 days before I finally got around to the problem. OMI-1.4.1-0 - Mon Nov 13 16:14:30 PST. I'll update to the above mentioned version.

**Comment by sundaxi** [comment] 2018-04-18 07:00
Hi, may I know which Team from Microsoft support for omi agent/server please?

**Comment by jeffaco** [comment] 2018-04-18 15:00
@sundaxi I sent you corporate E-Mail with appropriate contact information.

**Comment by JuliusPIV** [comment] 2018-04-19 19:56
hey @jeffaco - Just curious: Is an update with a fix going to get pushed automagically, should I open a case or should I run the script to unconfigure? (And if the latter, what are the drawbacks?)

**Comment by JumpingYang001** [comment] 2018-04-19 22:14
@JuliusPIV , if you used Azure box with enabling Diagnostic(Not have oms/omsagent installed), then you might need to update OMI to latest release by yourself? I am not sure about the latest omi version of enabling Diagnostic side.
If you used OMS, then it should automatically get pushed, but If you don't be pushed, I don't know the push your region date now.

Could you provide some info like 
1. are you installed OMS or enabling Diagnostic on Azure?
2. which is your oms and omi version now?
3. what is your Azure region?
4. what is your Operating System version?

**Comment by bimmerlabs** [comment] 2018-04-30 18:55
I have OMI-1.4.2-2 and I'm still getting this error (it actually just started again today).

I'm not using OMS (doesn't look like it's installed either), but I have Diagnostics enabled.  Ubuntu 16.04, West US.

The previous fix was just to comment out the chron job - not sure what happened or why it came back, I haven't changed anything.

**Comment by JumpingYang001** [comment] 2018-05-01 11:44
@bimmerlabs please make sure you don't have  /etc/krb5.keytab if you don't use Kerbros.
If you don't have above file, could you help to provide `crontab -l` output? thanks.

**Comment by JumpingYang001** [comment] 2018-05-03 03:12
@all, **make sure you don't do this action: ~~`touch /etc/krb5.keytab`~~** , if you done it before please remove it, thanks.

**Comment by AGLbwa** [comment] 2018-08-18 16:38
I notice the comments above about the fix for this going in. I also notice it's 2018-08-19 and I still (again?) have this issue. Was the fix not pushed or has there been a(nother?) regression pushed?

**Comment by AGLbwa** [comment] 2018-08-18 16:45
(Also, on SLES (can't speak to other distros), it's worse than the above as:
/opt/omi/bin/support/ktstrip: line 57: ktutil: command not found

# which ktutil
/usr/lib/mit/bin/ktutil

**Comment by JumpingYang001** [comment] 2018-08-20 02:01
@AGLbwa, can you provide your oms and omi version using `rpm -qa|grep oms`, `rpm -qa|grep omi` or  `dpkg -l|grep  oms`, `dpkg -l|grep omi`?

we fixed the ktutil issue on omi 1.4.3-1 and 1.5.0-0 in https://github.com/Microsoft/omi/commit/d8515971ca387fe90295f445c64c7bab294dfc2d#diff-c881a0050171e2a420cb95a8f4daae09

**Comment by mcbsys** [comment] 2018-08-22 16:01
Recently upgraded a server using sudo apt-get update && sudo apt-get dist-upgrade. I now show omsagent 1.6.0.163 and omi 1.4.2.5.

/var/spool/cron/crontabs/root contains

`* * * * * [ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab >/dev/null 2>&1 || true`

I guess the >/dev/null redirect is suppressing emails, which is good, but my syslog is filling with hundreds of omi messages. It seems an OMSConsistencyInvoker runs every 15 minutes, an omsagent logrotate every 5 minutes, and the keytab thing every minute. 

```
Aug 22 12:45:01 SERVER01 CRON[95716]: (omsagent) CMD (/opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1)
Aug 22 12:45:01 SERVER01 CRON[95717]: (root) CMD (/usr/sbin/logrotate /etc/logrotate.d/omsagent* >/dev/null 2>&1)
Aug 22 12:46:01 SERVER01 CRON[95836]: (root) CMD ([ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab >/dev/null 2>&1 || true)
Aug 22 12:47:01 SERVER01 CRON[95906]: (root) CMD ([ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab >/dev/null 2>&1 || true)

```
Is this normal? Should it be writing all these events to the main syslog?

**Comment by jeffaco** [comment] 2018-08-22 16:14
This issue is closed, perhaps a new issue should be opened here?

First, the OMS logs are part of a [different project](https://github.com/microsoft/oms-agent-for-linux), bugs against that should be logged there.

I'm ambivalent on if these should log. You can control if `crontab` messages are logged by system configuration. If you don't want to see `crontab` messages, you should turn them off. You can learn how to configure syslog via internet searches. If your system is configured to log `crontab` messages, then you should expect your system to log them.

As for OMI, though, I'm wondering if a better solution would be to set up (or clear) this crontab entry each time that OMI starts. When OMI starts, if Kerberos isn't enabled, get rid of the crontab entry. If Kerberos is enabled, then include the crontab entry. That way, if Kerberos isn't enabled (which is probably the 98+% use case), customers don't deal with this, ever.

Just a thought ...

**Comment by mcbsys** [comment] 2018-08-22 16:56
I'm not clear on what the original issue was so I don't know if this is new or not. Other than the urgency to stop emails every minute, is the underlying issue that it's running a process that does not apply to my machine? Is that still happening? How do I know if I have Kerberos enabled and if I don't, can I just delete that crontab entry? 

Like Windows Task Scheduler, I use crontab for periodic tasks. I definitely want crontab to log and email about my daily backup job and certbot status. But putting a system management task into crontab to run (and log, and email) every minute seems like a kludge. Shouldn't something like that be written as a service that runs continuously, with its own logs?

**Comment by jeffaco** [comment] 2018-08-22 17:15
The original problem was that, depending on system configuration, you'd get E-Mail because of cron job errors. But it was depending on system configuration, and thus Microsoft didn't catch it before release.

I'm no longer part of the OMI team. The thinking here: If you use Kerberos (you don't - if you did, you'd know it), you might need to change configuration settings. By making this a cron job, the administrator has full control over how Kerberos is handled. It was a good solution, giving system administrators ultimate control. But it created a rash of problems since there were problems associated with the implementation that were unknown at release time.

We talked about handing this maintenance task in OMI itself, but then it hides the fact that we're doing work to support Kerberos and, even worse, it severely restricts the customer's ability to customize Kerberos settings depending on their system configuration.

I'll leave this to the OMI team to figure out. You're the first one (that I'm aware of) that complained of the syslog crontab entries. Note that Linux itself uses crontab routinely for daily maintenance, so your syslog will have those anyway. It's just that those are being overshadowed by the OMI messages, and the OMS messages, since those are much more frequent.

In the short term, you can remove the entry from crontab. The problem is that any new installation of OMI will just put it back, so this is temporary. And even if you get rid of the OMI crontab entries, you still have the OMS crontab entries to contend with, and you need those for proper operation of OMS. For OMS, you'll need to raise this issue in [their repository](https://github.com/microsoft/oms-agent-for-linux).

**Comment by mcbsys** [comment] 2018-08-22 17:29
Thanks for the explanation. Running `sudo /opt/omi/bin/support/config_keytab_update.sh --unconfigure` for now. I guess I could put that in a cron job :).

**Comment by directhex** [comment] 2018-12-12 14:33
It's the end of 2018, and a brand new Ubuntu 18.04 VM still exhibits the *exact* same behaviour, courtesy of OMI 1.4.1.0

```

**Comment by bimmerlabs** [comment] 2018-12-12 16:17
I may be ignorant, but what does OMI even do?  Can we just remove it?  As far as I know, I am not using it for anything.  This is so annoying to still have this issue.

**Comment by JumpingYang001** [comment] 2018-12-13 02:39
@directhex @bimmerlabs I have no idea why the Azure still deploy the old omi version, can you help to create a ticket on Azure? thanks very much for help!

**Comment by JumpingYang001** [comment] 2018-12-13 02:43
OMI team don't manage Azure things, we only fixed the OMI issue long time again,  we don't know much about the Azure deployment team, thanks.

**Comment by JumpingYang001** [comment] 2018-12-13 03:09
@bimmerlabs as I know Diagnostic used mdsd which will call scx/omi for performance matrix, and OMS also call scx/omi for matrix, if you don't use Diagnostic and OMS or DSC, I think you can remove it, thanks.
