### ISSUE TITLE
RHEL7 + Centrify causing /tmp to fill up with krb5cc* files

### ISSUE THREAD

**Issue by Novahawkx** [microsoft/omi#620] opened 2019-03-12 15:24 UTC
I'm experiencing the following issues exactly as Centrify mentions on their site:

https://centrify.force.com/support/Article/KB-2297-tmp-filled-with-krb5cc-cdc-as-a-result-of-user-not-closing-session-properly

The problem is, it's impossible for Centrify to trigger background sweep since the omi PID is always the same and always has a session. It seems that omi is triggering PAM which adclient (Centrify) is processing, but omi is never sending pam_close_session causing the tokens to pile up quickly.

Also to add, the account that omi runs as is a domain based account for ease of password management and sudoers management.

**Comment by JumpingYang001** [comment] 2019-03-12 21:59
hello, it is duplicated with #570 , and we fixed it in #571 .
it is in omi 1.6.0 release.

**Comment by JumpingYang001** [comment] 2019-03-12 22:06
omi is a service account without any logins, its purpose is let most of http/socket requests to omi run as a non-root daemon called omiengine to be more secure on process level like apache run as apache user.

**Comment by JumpingYang001** [comment] 2019-03-12 22:14
omi user is a local user.
for Kerberos authentication of omi, it use user-defined users to auth instead of omi user itself, omi user is only a non-root user to launch omiengine which will dealt with most of the requests from users, the users are the omi providers, they wrote omi providers like scx, dsc, and they request omi to run omi providers.

**Comment by JumpingYang001** [comment] 2019-03-12 22:15
for PAM, yes, we use PAM as local users authentication verification.

**Comment by JumpingYang001** [comment] 2019-03-12 22:18
@Novahawkx in short, /tmp files are not related to PAM, it was a script issue, we have fixed it in omi 1.6.0.

**Comment by JumpingYang001** [comment] 2019-03-12 22:24
@Novahawkx ho, just found it is different file names, so your issue is different with my mentioned one, I will check the issue today.

**Comment by JumpingYang001** [comment] 2019-03-12 22:53
I check.the code righr now, we call pam_end instead of pam_close_session here: https://github.com/Microsoft/omi/blob/master/Unix/base/user.c#L157
so it might not be an issue on omi side, but let me investigate it to figure out how omi can do at the krb files under /tmp.

**Comment by JumpingYang001** [comment] 2019-03-12 23:06
@Novahawkx as my understanding, omi call Kerberos library and Kerberos library create krb cached files, I am not sure if there is some relationship between Kerberos and PAM. because it seems PAM only for local users.  can you share your omi version, Operating System  version and Kerberos software and version? so I can repro the issue, thanks.

**Comment by Novahawkx** [comment] 2019-03-14 12:42
@JumpingYang001 When you utilize Centrify on a Linux machine, it replaces PAM with it's own shim that allows domain users to be treated as local users, allowing Kerberos to function for domain accounts and let them access *NIX machines.

As for versions:

1) CentrifyDC 5.4.1-455
2) /etc/redhat-release: Red Hat Enterprise Linux Server release 7.6 (Maipo)
3) Uname -a shows on RHEL7 machine: 3.10.0-957.1.3.el7.x86_64
4) /opt/omi/bin/omiserver: OMI-1.4.2-5 - Wed Jul 25 10:59:15 PDT 2018

**Comment by JumpingYang001** [comment] 2019-03-15 02:48
@Novahawkx thanks for sharing it! but I never used CentrifyDC before, could you help to provide a reproduce steps with detailed commands on RedHat7.6? so I can go the same way with you.

**Comment by Novahawkx** [comment] 2019-03-18 08:38
@JumpingYang001 Here's what we have to reproduce:

1) We have CentfifyDC installed on the machine
2) Machine is then domain joined with Centrify
3) Centrify is configured to allow multiple kerberos sessions per user (this is key to reproducing this issue)
3) Account that OMI runs as is a domain account
4) Log in as the domain user that will be running the service
5) Install OMI manually, let run automatically

From there you should see /tmp filling up with these krb5cc files.

**Comment by JumpingYang001** [comment] 2019-03-18 09:36
Hi @Novahawkx , for "omi run as a domain account", do you mean omiserver or omiengine process run as a domain user?  I never see this kind of scenarios before, I don't quite understand if your user have to use Kerberos to auth with omiserver?
we also have binary protocol for local communicate with omiserver, and also Basic and Negotiate authentication for remoting, if you don't want Kerberos to authentication with omi, we have provided a way to purge omi Kerberos setting in omi 1.6.0 :
1. `sudo /opt/omi/bin/support/config_keytab_update.sh  --purgeforever`
2. `sudo rm -rf /etc/opt/omi/creds/omi.keytab` 
3. `sudo /opt/omi/bin/service_control restart`

please let me know how to do step 4: "4.Account that OMI runs as is a domain account", thanks.
BTW, do you have testing env? I don't have access to centrify resources, maybe we can communicate with email: v-zhenpy@microsoft.com

**Comment by Novahawkx** [comment] 2019-03-18 10:30
@JumpingYang001 Yes, OMI runs as a domain account, because Centrify makes the domain account appear to be a local account. From what I understand it doesn't seem to be anything related to Kerberos itself, but to how OMI is calling PAM without doing pam_end_session after it's finished.

**Comment by JumpingYang001** [comment] 2019-03-19 03:31
@Novahawkx, thanks for sharing it! please send an email to my email: v-zhenpy@microsoft.com, I will make a test build for you to add pam_close_session instead of pam_end, then let's check if it can fix your issue.
once it can fix the issue, I will new a PR and request review to our team.

**Comment by JumpingYang001** [comment] 2019-03-21 03:16
discussed offline.

**Comment by JumpingYang001** [comment] 2019-04-01 02:39
will close once the fixes be merged, thanks.

**Comment by satyavadali** [comment] 2019-04-05 21:28
surprised; this issues we reported in Nov last year through internal MS channel - packet loss!
other issues:
-- Kerberos auth should only be enabled for supported / tested products. ( Centrify: make it optional)
-- Scan agent install using commercial off the shelf security tools

**Comment by JumpingYang001** [comment] 2019-04-08 02:56
@satyavadali I don't know related stories about packet loss, I have new a PR to fix the pam_close, any other fixes need? I never got any related issue reported inner MS, if you have any thing need to fix, you can contact my MS manager(OMI team).

**Comment by JumpingYang001** [comment] 2019-05-09 05:04
Fixed, wait next release.

**Closed by JumpingYang001** 2019-05-09 05:04 UTC
